[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link" }

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo"}
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "keyboard",
    "--",
    "-O",
    "ihex",
    "kb.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]
